### ISSUE TITLE
moda_oc_7d_gom failing : colorbarMax == colorbarMin

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/erddap-config#40]
Error from DasDds:

```
Caused by: java.lang.IllegalArgumentException: colorBarMinimum=-25000.035 must be less than colorBarMaximum=-25000.035.
```

I suspect one of the colorbar values needs to be changed here:

https://github.com/USF-IMARS/erddap-config/blob/7d3177661ad02fb03990e3446f28cc59c07270ba/datasets/moda_oc_7d_gom/dataset.xml#L79-L80

**Comment by dotis** [comment]
Got it. Thanks.

Working on the repeated files in other directories.
________________________________

**Comment by dotis** [comment]
The following datasets should be fixed in terms of repeated files:

/mnt/sdb/moda_oc_7d_fk
/mnt/sdb/moda_sst4_7d_fk
/mnt/sdb/moda_oc_7d_fgb
/mnt/sdb/moda_sst4_7d_fgb
/mnt/sdb/vsnpp_oc_7d_fk
/mnt/sdb/vsnpp_sstn_7d_fk

I am re-making the GOM datasets with new products.
________________________________

**Comment by dotis** [comment]
This is sort of a vexing issue. The files appear to be replaced on dune only if the filenames are the same. Old files that we don't want are kept for some reason. I need to look more into the rsync syntax.
________________________________
